version: "3.9"

services:
  image-registry:
    container_name: image-registry
    image: registry:latest
    volumes:
      - ../data/image-registry:/var/lib/registry
    ports:
      - 5000:5000
    restart: always