version: "3"
services:
  image-registry:
    container_name: image-registry
    image: registry:latest
    volumes:
      - storage/image-registry:/var/lib/registry
    ports:
      - 5000:5000
    restart: always
    env_file:
      - .env

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 22818:2181
    env_file:
      - .env

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - 29092:29092
    env_file:
      - .env
    depends_on:
      - zookeeper